#!/bin/bash
BACKUP_FILE=/tmp/dump.sql
HOST=0.0.0.0

echo "开始备份数据库..."
mysql -uroot -h ${HOST} -e "show databases" |
    grep "db_silver" |
    xargs -I '{}' mysqldump --column-statistics=0 -uroot -h ${HOST} --databases '{}' \
        --default-character-set=utf8 --max_allowed_packet=48M \
        --ignore-table=db_silver_ins_common_tcp.r_delayed_job \
        --ignore-table=db_silver_ins_common_tcp.o_job \
        >$BACKUP_FILE
echo "备份数据库完成"

echo "开始导入数据库..."
mysql -uroot -e "SET GLOBAL innodb_flush_log_at_trx_commit=0;
SET GLOBAL sync_binlog=0;
SET sql_log_bin=off;
source /tmp/dump.sql;
SET GLOBAL innodb_flush_log_at_trx_commit=1;
SET GLOBAL sync_binlog=1;"
echo "导入数据库完成"
