#! /bin/bash
QUERY=""
if [[ $# -ne 0 ]]; then
    QUERY="$1"
fi
target=$(
    pm2 l |
        awk '{print $4}' |
        grep -E '[^(name)|\s+|(`pm2)]' |
        fzf -m -q "${QUERY}" -1
)

if [ -n "${target}" ]; then
    pm2 delete ${target}
fi
