version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    platform: linux/arm64
    networks:
      - app-tier
    hostname: zookeeper
  kafka:
    hostname: kafka
    image: bitnami/kafka:latest
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/local/bin/docker:/usr/bin/docker
      - ../script/j:/usr/bin/j
      - ../script/get_docker_network_name:/usr/bin/get_docker_network_name
      - ../script/fzf:/usr/bin/fzf
      - ../entrypoint/bash.sh:/usr/bin/bash.sh
    platform: linux/arm64
    networks:
      - app-tier
networks:
  app-tier:
      driver: bridge

