version: "2.1"
services:
  project:
    image: node:10.15.0
    tty: true
    stdin_open: true
    environment:
      - LC_ALL=C.UTF-8
      - TZ='Asia/Shanghai'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - ../script/j:/usr/bin/j
      - ../script/get_docker_network_name:/usr/bin/get_docker_network_name
      - ../script/fzf:/usr/bin/fzf
      - ../entrypoint/project.sh:/usr/bin/project_entrypoint.sh
      - ../entrypoint/bash.sh:/usr/bin/bash.sh
    entrypoint: /usr/bin/project_entrypoint.sh
