#!/bin/bash
DOCKER_NAME=$(get_docker_network_name)
case $DOCKER_NAME in
*-project-*)
    USER_NAME=node
    WORK_DIR=/home/node
    ;;
'')
    exit -1
    ;;
*)
    USER_NAME=root
    WORK_DIR=/root
    ;;
esac
sudo docker exec --user $USER_NAME --workdir $WORK_DIR -it $DOCKER_NAME /bin/bash
